clipper @rac   -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrnt  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrnt1 -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrnt2 -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rres  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rccp  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rinv  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rmkt  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rdyp  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrpt  -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rsys  -o..\OBJ
            if errorlevel 1 goto exit 
clipper rafunc -o..\OBJ
            if errorlevel 1 goto exit 
 clipper rafunc1  -o..\OBJ
             if errorlevel 1 goto exit 
 clipper rafunc2  -o..\OBJ
             if errorlevel 1 goto exit 
 clipper rafunc3  -o..\OBJ
             if errorlevel 1 goto exit 
 clipper rafunc4  -o..\OBJ
             if errorlevel 1 goto exit 
 clipper alterror  -l -o..\OBJ
             if errorlevel 1 goto exit 
:EXIT
